### PR TITLE
Feature print stylesheet reports

### PR DESCRIPTION
**Pull request by AdamChlan**
@mmontesanonyc this work represents the design mockup you approved recently. our work has focused in Chrome to this point.

### CODE REVIEW

**Comment by mmontesanonyc** [comment]
Thanks, @AdamChlan - this is looking great. Big picture, if I understand it, is that `d-print-none` gets rid of things we don't want, and then in `report_indicator.html`, we've got `d-print-none` on the standard indicator display, and a rebuilt, `print-only` indicator display. Anything else high level we should pay attention to, here?

**Comment by AdamChlan** [comment]
@mmontesanonyc that is right. `d-print-none` comes with bootstrap so I leveraged that. I added in the `print-only ` class.

I did have to write some print specific CSS for various text and other elements to achieve the layout. I tried to do as little of that as possible. Also needed to add some additional markup to the template for print only, and again, tried to not go overboard there.

**Comment by AdamChlan** [comment]
@mmontesanonyc would you like us to open up a PR to the production branch?

**Comment by mmontesanonyc** [comment]
Thanks, @AdamChlan, but no need for now. We're going to run this by a few folks on our and and then merge to prod and deploy this week or early next.

**Pull request merged**
