### PR TITLE
Hotfix rtaq for prod

### PR DESCRIPTION
**Pull request by mmontesanonyc**

### CODE REVIEW

**Comment by mmontesanonyc** [comment]
@cgettings, you revised the workflows, right?  I'm getting post merge build errors on prod:

image

**Comment by mmontesanonyc** [comment]
Oh wait - that has to do with the protection rule I just made.

**Comment by cgettings** [comment]
I thought I had fixed this by adding us as exceptions

**Comment by mmontesanonyc** [comment]
I just pulled the rule off for production, but the action still got hung up on data-staging. Git conflict? Have our branches gotten out of whack? 

https://github.com/nychealth/EH-dataportal/actions/runs/3989702928/jobs/6842732709

**Comment by cgettings** [comment]
try an empty commit on `hotfix-rtaq-for-prod` and then PR again

**Pull request merged**
