### PR TITLE
Feature-all-site-changes-2023-12 (prod)

### PR DESCRIPTION
**Pull request by cgettings**
Just need to do a little more poking around, then these site changes will be ready to go!

For the record: different DE data format, different NR data structure, ability to turn off charts for year x geo combos, different comparisons/trend functionality, changed how URLs are specified in Hugo code.

### CODE REVIEW

**Review by cgettings — COMMENTED** [review]
Just realized that this has some mreges from development, so... will have to straighten that out. @mmontesanonyc Could you take a look to see if any of the commits from dev shouldn't make it onto prod?

**Comment by mmontesanonyc** [comment]
I just unpublished something that was on dev and shouldn't be on prod; let's plan to review this together before merging into prod, too - I want to make sure I understand the changes in here.

I also think it might be a good idea to serve this on CC and run through the QA checklist - due diligence before deploying substantial changes.

**Review by cgettings — COMMENTED** [review]
@mmontesanonyc I think I got this all straightened out. I'll plan to deploy next week. In the meantime, if you want to deploy your recent merges go for it. Also, if you want to poke around the CC branch and try to break things, please do.

**Comment by cgettings** [comment]
Bugs are squashed 👍

**Review by cgettings — COMMENTED** [review]
MORE bugs are squashed

**Review by cgettings — COMMENTED** [review]
Also tackled #700 in the bargain

**Pull request merged**
