### PR TITLE
first pass at Pagefind

### PR DESCRIPTION
**Pull request by AdamChlan**
@mmontesanonyc this PR represents a first pass at showing how Pagefind could work for site search. I believe there is a way for you to test this work locally, with a few steps. I'm not sure if you've been doing that with other PRs I have opened or just merging into development to do your testing there. This one may be best to test locally first, but I'll leave that up to you.

If you click on the search icon you will be taken to a dedicated search page where you can do some testing. We set up an example of filter, but this can be expanded upon as needed.

### CODE REVIEW

**Comment by mmontesanonyc** [comment]
Thanks, Adam. I ran `npm update` and served it up locally, but the search page is showing blank and the console is showing errors trying to find pagefind's css and js. Is there something else I need to do on my end? 

image

**Comment by AdamChlan** [comment]
@mmontesanonyc Yes, for running local please run the following:

This will create an index in the static directory. This does not get committed to the repo, but does allow us to test locally.
`npm_config_yes=true npx pagefind --source "docs" --bundle-dir ../static/_pagefind`

Then run

`hugo server --disableFastRender `

**Comment by mmontesanonyc** [comment]
Thanks! Got it. It's actually:
`npm_config_yes=true npx pagefind --source "docs" --bundle-dir ../static/pagefind` 
(/pagefind vs /_pagefind)

NB @cgettings and @etorem for when you also test.

**Comment by AdamChlan** [comment]
@mmontesanonyc thanks for catching that. I did read that GitHub pages can't serve content out of a directory with an underscore, so I did stray from the docs a bit.

**Comment by mmontesanonyc** [comment]
That makes sense.

So presumably, in Github Actions, we'd need to add that line as part of the build step, right? Currently we have this in our [GHAs](https://github.com/nychealth/EH-dataportal/blob/production/.github/workflows/hugo-build-to-gh-pages.yml)

```
      # run gruntfile action

      - name: Build index with Grunt
        run: |
          cd '${{ github.workspace }}'
          grunt lunr-index --stack
```

...and we'd need to replace that command with this command to index with pagefind. right?

**Comment by AdamChlan** [comment]
I believe simply adding `npx pagefind` will do the trick. We can add some additional configurations to the pagefind.yml file to simplify the command. We'll also want to run that command on Cloudcannon when content is changed, and the site builds. In case content is being added/edited directly in the CMS.

**Comment by mmontesanonyc** [comment]
Thanks!

Do you mind opening a PR instead into `feature-pagefind-search`? I think we might like to fiddle with it a bit before pulling it into dev, and have a branch we can both contribute to.

**Comment by AdamChlan** [comment]
@mmontesanonyc Okay, PR opened into that branch. I added the bundle directory to the page find config.

**Pull request closed without merging**
