### PR TITLE
Hotfix add job ID

### PR DESCRIPTION
**Pull request by mmontesanonyc**

### CODE REVIEW

**Comment by mmontesanonyc** [comment]
@cgettings - got a PR to `development` throwing a bunch of merge conflicts. Scanning this, I'm assuming it's based on integrity work and some of the other pipeline work you've done recently - are you planning to update `development` from `production` so we can merge into both cleanly?

**Comment by cgettings** [comment]
@mmontesanonyc dev is currently serving the bundled data explorer, which changes a lot of stuff. Too spooked to merge right before the weekend. I’ll make sure everything’s working, merge the changes to prod, and then maybe fast forward this PR branch. That will probably do it.

**Comment by mmontesanonyc** [comment]
ah gotcha! nice, didn't realize the bundling was on dev. nice. that sounds like a good plan. i just plopped a few things onto production regardless, so a deploy later on this week would be good.

**Comment by cgettings** [comment]
Which will provide a nice in vivo test of the check-deploy action

**Comment by mmontesanonyc** [comment]
Lookin' forward to seeing that email! 💯

**Pull request merged**
